version: '3.9'

services:
  api:
    restart: always
    ports:
      - "8000:80"
    image: crud-api
    depends_on:
      - db
    container_name: compose-api
  db:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banco-app
    ports:
      - "5432:5432"
    container_name: compose-banco-container

